version: '3'
services:
  db:
    container_name: bl_postgres
    image: postgres
    restart: always
    networks:
      - web
    ports:
      - "4444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  pgadmin:
    container_name: bl_pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - web
    ports:
      - "3333:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

networks:
  web:
    external: true
